package com.github.rccookie.interpreter.tokenizer;

public enum TokenType {

    COMMENT,
    TEXT,

    MODIFIER,
    ANY_TYPE,
    PRIMITIVE,
    CLASS_TYPE,
    REFERENCE,

    ANY_CONTEXT,
    COMPARATOR,
    BOOLEAN_COMPARATOR,
    BOOLEAN_OPERATOR,
    OPERATOR,
    MATH_OPERATOR,
    SINGLE_OPERATOR,
    ASSIGNMENT,
    INCREASEMENT,

    BREAKING,

    CONTROL_STRUCTURE,
    LOOP,

    FOLLOWING_TRY,
    FOLLOWING_CLASS_TYPE,

    NEW_LINE_REASON,
    PREFERES_WHITESPACE_BEFORE,
    PREFERES_WHITESPACE_AFTER,

    UNSPECIFIED,
    IDENTIFIER,
    HARDCODED_CHAR,
    HARDCODED_STRING,
    SINGLE_LINE_COMMENT,
    MULTI_LINE_COMMENT;
}
